language: php
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
before_script:
  - cp ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ~/.phpenv/xdebug.bak.ini
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer install
script:
  - vendor/bin/phing
after_script:
  - phpenv config-add ~/.phpenv/xdebug.bak.ini
  - php vendor/bin/coveralls -v
